# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

target "Bafit" do

pod 'JSQMessagesViewController', '5.1.1'
pod 'AFNetworking', '~> 2.0'

end

target "BafitTests" do

end

