# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

target "Bafit" do

pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
pod 'AFNetworking', '~> 2.0'

end

